# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

khatri_rao_pair_cpp <- function(A, B, reverse = FALSE) {
    .Call(`_tensory_khatri_rao_pair_cpp`, A, B, reverse)
}

mttkrp_blas_cpp <- function(tensor_data, factors, mode) {
    .Call(`_tensory_mttkrp_blas_cpp`, tensor_data, factors, mode)
}

mttkrps_cpp <- function(tensor_data, factors) {
    .Call(`_tensory_mttkrps_cpp`, tensor_data, factors)
}

mttkrp_cpp <- function(tensor_data, factors, mode) {
    .Call(`_tensory_mttkrp_cpp`, tensor_data, factors, mode)
}

fibers_cpp <- function(tensor_data, mode, midx) {
    .Call(`_tensory_fibers_cpp`, tensor_data, mode, midx)
}

contract_cpp <- function(tensor_data, mode1, mode2) {
    .Call(`_tensory_contract_cpp`, tensor_data, mode1, mode2)
}

mask_cpp <- function(tensor_data, mask_data) {
    .Call(`_tensory_mask_cpp`, tensor_data, mask_data)
}

issymmetric_cpp <- function(tensor_data, grps) {
    .Call(`_tensory_issymmetric_cpp`, tensor_data, grps)
}

dense_dot_cpp <- function(x, y) {
    .Call(`_tensory_dense_dot_cpp`, x, y)
}

gram_cpp <- function(tensor_data, mode) {
    .Call(`_tensory_gram_cpp`, tensor_data, mode)
}

t_scale_cpp <- function(tensor_data, s, modes) {
    .Call(`_tensory_t_scale_cpp`, tensor_data, s, modes)
}

symmetrize_cpp <- function(tensor_data, grp) {
    .Call(`_tensory_symmetrize_cpp`, tensor_data, grp)
}

#' @keywords internal
#' @noRd
spgtr_mode_covs_cpp <- function(Xt, dims) {
    .Call(`_tensory_spgtr_mode_covs_cpp`, Xt, dims)
}

#' @keywords internal
#' @noRd
spgtr_slpg_cpp <- function(G0, M, MUinv, gam, maxit, tol, ridge = 1e-10) {
    .Call(`_tensory_spgtr_slpg_cpp`, G0, M, MUinv, gam, maxit, tol, ridge)
}

ttm_cpp <- function(tensor_data, matrix, mode, transpose = FALSE) {
    .Call(`_tensory_ttm_cpp`, tensor_data, matrix, mode, transpose)
}

ttm_multiple_cpp <- function(tensor_data, matrices, modes, transpose = FALSE) {
    .Call(`_tensory_ttm_multiple_cpp`, tensor_data, matrices, modes, transpose)
}

