# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ttm_cpp <- function(tensor_data, matrix, mode, transpose = FALSE) {
    .Call(`_tensory_ttm_cpp`, tensor_data, matrix, mode, transpose)
}

ttm_multiple_cpp <- function(tensor_data, matrices, modes, transpose = FALSE) {
    .Call(`_tensory_ttm_multiple_cpp`, tensor_data, matrices, modes, transpose)
}

